# ============================================================
# СБОРКА ВСЕХ ТЕКСТОВ
# ============================================================
from .compliments import COMPLIMENTS
from .warm import WARM
from .good_morning import GOOD_MORNING
from .good_night import GOOD_NIGHT
from .love_you import LOVE_YOU
from .miss_you import MISS_YOU
from .poems import POEMS
from .quotes import QUOTES
from .flirt import FLIRT
from .care import CARE
from .jokes import JOKES
from .surprises import SURPRISES
from .reasons import REASONS_LOVE
from .about_you import ABOUT_YOU
from .dates import DATES
from .movies import MOVIES
from .series import SERIES
from .books import BOOKS
from .dinner import DINNER_IDEAS
from .gifts import GIFTS
from .future import FUTURE
from .cards import CARDS
from .quiz import QUIZ_QUESTIONS
from .truth_dare import TRUTH_OR_DARE
from .love_cards import LOVE_CARDS
from .achievements import ACHIEVEMENTS
from .moods import MOODS
from .sleeps import SLEEPS
from .thoughts import THOUGHTS
from .letters_ascii import LETTERS_ASCII
from .secrets import SECRET_TEXTS